site_name: Webconf service manual pages
docs_dir: ./

pages:

- Home: 'index.md'

- FAQ: 'faq.md'

#   - Technical details: 'fokia/details.md'
#   - Usage: 'fokia/usage.md'
#
#
# - Service API:
#   - Technical details: 'service-api/details.md'
#   - Usage: 'service-api/index.md'
#   - Authentication: 'service-api/Authentication.md'
#   - Create Lambda Instance: 'service-api/CreateLambdaInstance.md'
#   - List Lambda Instances: 'service-api/LambdaInstancesList.md'
#   - Count Lambda Instances: 'service-api/LambdaInstancesCount.md'
#   - Details of a Lambda Instance: 'service-api/LambdaInstanceDetails.md'
#   - Actions on a Lambda Instance: 'service-api/LambdaInstanceAction.md'
#   - Destroy a Lambda Instance: 'service-api/LambdaInstanceDestroy.md'
#   - Upload an Application: 'service-api/ApplicationUpload.md'
#   - Delete an Application: 'service-api/ApplicationDelete.md'
#   - List Applications: 'service-api/ApplicationsList.md'
#   - Count Applications: 'service-api/ApplicationsCount.md'
#   - Details of an Application: 'service-api/ApplicationDetails.md'
#   - Deploy an Application: 'service-api/ApplicationDeploy.md'
#   - Withdraw an Application: 'service-api/ApplicationWithdraw.md'
#   - List Deployed Applications: 'service-api/ApplicationsListDeployed.md'
#   - Start an Application: 'service-api/ApplicationStart.md'
#   - Stop an Application: 'service-api/ApplicationStop.md'
#   - Get SSH public keys on ~okeanos: 'service-api/UserPublicKeys.md'
#   - Get allowed VM Parameter Values: 'service-api/VMParameterValues.md'
#   - Get User ~okeanos Projects: 'service-api/UserOkeanosProjects.md'
#
# - Central API:
#   - Details: 'central-api/details.md'
#   - 'Description': 'central-api/index.md'
#   - 'User API calls': 'central-api/API_users.md'
#   - 'Lamdba Instances API calls': 'central-api/API_lambda_instances.md'
#   - 'Lamdba Applications API calls': 'central-api/API_lambda_applications.md'
#
# - Administration:
#   - Service VM image: 'admin/service.md'
#   - Lambda nodes images: 'admin/lambda.md'
#   - Service Messages: 'admin/messages.md'

#
# - 'License': 'about/license.md'


theme: readthedocs
